services:
  mlflow-ui:
    build:
      dockerfile: ui.Dockerfile
    ports:
      - "5000:5000"
  mlflow-inference:
    build:
      dockerfile: inference.Dockerfile
    network_mode: host
    ports:
      - "5002:5002"